apiVersion: v1
kind: Service
metadata:
  name: lanchonete-producao
  namespace: app
spec:
  type: ClusterIP  
  selector:
    app: lanchonete-producao
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000